export const TICKET_REQUEST = "TICKET_REQUEST";
export const TICKET_FAIL = "TICKET_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAIL = "GET_TICKET_FAIL";
export const GET_TICKET_REQUEST = "GET_TICKET_REQUEST";
export const TICKET_CREATE = "TICKET_CREATE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";
export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const EDIT_TICKET_SUCCESS = "EDIT_TICKET_SUCESS";
export const EDIT_TICKET_FAIL = "EDIT_TICKET_FAIL";
export const EDIT_TICKET_REQUEST = "EDIT_TICKET_REQUEST";







